version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-test:9092
    depends_on: 
      - kafka-test
    networks:
      - test

  zookeeper-test:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - test

  kafka-test:
    image: 'bitnami/kafka:latest'
    container_name: kafka-test
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-test:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-test:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-test
    networks:
      - test

networks:
  test:
    driver: bridge